### ISSUE TITLE
Database not included?

### ISSUE THREAD

**Issue by Hershef** [Senpaiyaa/Point-Of-Sale#1]
Database not included?

**Comment by Senpaiyaa** [comment]
I've totally missed that. Thank you for reminding me. I have to dig through my files to find the database. Maybe I can upload it this coming weekend. I almost forgot about this project since this is a pretty old repo. This diagram is the closest thing I can provide for the working back-end. Apologies. 

![erd-updated](https://user-images.githubusercontent.com/42696014/62230687-ebbdfe00-b3f4-11e9-9640-b8dadc96c70d.png)

**Comment by Senpaiyaa** [comment]
@Hershef you need to download the database on the link below and I also included the accounts available for the admin and staff access. Try to experiment on this one on your localhost. 

Database: https://drive.google.com/open?id=1ZKnHJuF95rWR14nD_Wo1WloHOuMncs_j
Accounts: https://drive.google.com/open?id=1ZZ6TpWMwiaIeENd-FqGIDFmLMdbIkjJo
